import GenLimit
import Lean.Util.CollectAxioms
import Lean.Elab.Command

open Lean Elab Command

private def allowedAxioms : Array Name :=
  #[``propext, ``Classical.choice, ``Quot.sound].qsort Name.lt

/-- Fail unless a declaration uses exactly the project's allowed logical dependencies. -/
elab "assert_axioms " n:ident : command => do
  let name ← liftCoreM <| Lean.Elab.realizeGlobalConstNoOverloadWithInfo n
  let actual := (← Lean.collectAxioms name).qsort Name.lt
  unless actual == allowedAxioms do
    throwError m!"unexpected axioms for {name}: {actual.toList}; expected {allowedAxioms.toList}"
  logInfo m!"{name}: {actual.toList}"

/-- Fail if a declaration introduces anything outside the project allowlist.
Constructive declarations may use a strict subset of the three principles. -/
elab "assert_allowed_axioms " n:ident : command => do
  let name ← liftCoreM <| Lean.Elab.realizeGlobalConstNoOverloadWithInfo n
  let actual := (← Lean.collectAxioms name).qsort Name.lt
  unless actual.all fun ax => allowedAxioms.contains ax do
    throwError m!"unexpected axioms for {name}: {actual.toList}; allowed {allowedAxioms.toList}"
  logInfo m!"{name}: {actual.toList}"

assert_axioms GenLimit.KM.Semantic.kleinbergMullainathan_main
assert_axioms GenLimit.OracleFamily.kleinbergMullainathan_main
assert_axioms GenLimit.OracleFamily.ArxivV1.kleinbergMullainathan_main
assert_axioms GenLimit.KM.SetInterface.kleinbergMullainathan_set_interface
assert_axioms GenLimit.KM.SetInterface.kleinbergMullainathan_set_interface_with_repetitions
assert_axioms GenLimit.LiRamanTewari.uniform_implies_nonuniform
assert_axioms GenLimit.LiRamanTewari.nonuniform_implies_limit
assert_axioms GenLimit.LiRamanTewari.closure_dimension_necessity
assert_allowed_axioms GenLimit.LiRamanTewari.closureGenerator_isUniformGeneratorAt
assert_axioms GenLimit.LiRamanTewari.closure_dimension_sufficiency
assert_axioms GenLimit.LiRamanTewari.finite_closure_dimension_implies_uniform
assert_axioms GenLimit.LiRamanTewari.uniform_generatability_iff_finite_closure_dimension
assert_allowed_axioms GenLimit.LiRamanTewari.closure_witness_defeats_uniform_threshold
assert_allowed_axioms GenLimit.LiRamanTewari.uniform_threshold_mono
assert_allowed_axioms GenLimit.LiRamanTewari.uniformGenerationSampleComplexity_eq_top_iff
assert_allowed_axioms GenLimit.LiRamanTewari.uniformGenerationSampleComplexity_lt_top_iff
assert_allowed_axioms GenLimit.LiRamanTewari.uniformGenerationSampleComplexity_le_coe_iff
assert_allowed_axioms GenLimit.LiRamanTewari.uniformGenerationSampleComplexity_eq_coe_iff
assert_allowed_axioms GenLimit.LiRamanTewari.uniformlyGeneratable_iff_exists_sampleComplexity_lt_top
assert_allowed_axioms GenLimit.LiRamanTewari.optimalUniformGenerationSampleComplexity_eq_top_iff
assert_allowed_axioms GenLimit.LiRamanTewari.optimalUniformGenerationSampleComplexity_le_coe_iff
assert_allowed_axioms GenLimit.LiRamanTewari.closure_dimension_le_uniform_threshold
assert_allowed_axioms GenLimit.LiRamanTewari.closure_dimension_le_uniformGenerationSampleComplexity
assert_allowed_axioms GenLimit.LiRamanTewari.closureGenerator_uniformGenerationSampleComplexity_le
assert_allowed_axioms GenLimit.LiRamanTewari.closure_dimension_le_optimalUniformGenerationSampleComplexity
assert_allowed_axioms GenLimit.LiRamanTewari.optimalUniformGenerationSampleComplexity_le_closureDimension_succ
assert_allowed_axioms GenLimit.LiRamanTewari.optimal_uniform_generation_sample_complexity_bounds
assert_axioms GenLimit.LiRamanTewari.nonuniform_characterization_necessity
assert_axioms GenLimit.LiRamanTewari.nonuniform_characterization_sufficiency
assert_axioms GenLimit.LiRamanTewari.nonuniform_generatability_iff_nondecreasing_finite_closure_cover
assert_axioms GenLimit.LiRamanTewari.finite_language_class_has_finite_closure_dimension
assert_axioms GenLimit.LiRamanTewari.countable_classes_are_nonuniformly_generatable
assert_allowed_axioms GenLimit.LiRamanTewari.theorem_2_4
assert_axioms GenLimit.LiRamanTewari.finite_closure_dimension_cover_implies_generatable_in_limit
assert_axioms GenLimit.LiRamanTewari.exists_uncountable_uniformly_generatable_class
assert_axioms GenLimit.LiRamanTewari.exists_countable_nonuniform_not_uniform_class
assert_axioms GenLimit.LiRamanTewari.finite_union_of_paper_cone_classes_generatable_in_limit
assert_axioms GenLimit.LiRamanTewari.exists_generatable_in_limit_not_nonuniformly_generatable
assert_axioms GenLimit.LiRamanTewari.exists_two_zero_closure_classes_union_not_nonuniform
assert_axioms GenLimit.LiRamanTewari.exists_countable_sequence_zero_closure_union_not_limit
assert_axioms GenLimit.LiRamanTewari.theorem_4_1_i_combinatorial_core
assert_axioms GenLimit.LiRamanTewari.theorem_4_1_ii_combinatorial_core
assert_axioms GenLimit.LiRamanTewari.theorem_4_1_iii_combinatorial_core
assert_axioms GenLimit.LiRamanTewari.theorem_4_1_iv_combinatorial_core
assert_axioms GenLimit.LiRamanTewari.theorem_4_1_v_combinatorial_core
assert_axioms GenLimit.LiRamanTewari.theorem_4_1_vi_combinatorial_core
assert_axioms GenLimit.LiRamanTewari.theorem_4_1_combinatorial_core
assert_axioms GenLimit.LiRamanTewari.prompted_uniform_generatability_iff_finite_prompted_closure_dimension
assert_axioms GenLimit.LiRamanTewari.prompted_nonuniform_generatability_iff_nondecreasing_finite_closure_cover
assert_axioms GenLimit.LiRamanTewari.finite_prompt_classes_are_uniformly_generatable
assert_axioms GenLimit.LiRamanTewari.countable_prompt_classes_are_nonuniformly_generatable
assert_axioms GenLimit.LiRamanTewari.countable_prompt_classes_are_generatable_in_limit
assert_axioms GenLimit.LiRamanTewari.exists_finite_prompt_class_not_uniformly_generatable
assert_axioms GenLimit.LiRamanTewari.exists_finite_prompt_class_not_nonuniformly_generatable
assert_axioms GenLimit.LiRamanTewari.exists_nonuniformly_generatable_not_eventuallyUnboundedClosure
assert_axioms GenLimit.LiRamanTewari.printed_EUC_equivalence_is_false
assert_axioms GenLimit.LiRamanTewari.theorem_C2_finite_eventually_unbounded_closure_cover
assert_axioms GenLimit.LiRamanTewari.theorem_C4_eventually_unbounded_closure
assert_axioms GenLimit.PatientMachine.patient_validity
assert_axioms GenLimit.PatientMachine.settledChargingCertificate
assert_axioms GenLimit.PatientMachine.patientScope_lowerDensity_half
assert_axioms GenLimit.PatientMachine.patientScope_generation_and_lowerDensity
assert_axioms GenLimit.PartialEnumeration.Counterexample.output_not_mem_trueLanguage
assert_axioms GenLimit.PartialEnumeration.lemma_3_16_generation
assert_axioms GenLimit.PatientScope.PartialEnumerationCertificate.theorem_3_17
assert_axioms GenLimit.PartialEnumeration.theorem_3_17_lowerDensity
assert_axioms GenLimit.PartialEnumeration.theorem_3_17
assert_axioms GenLimit.Gold.Abstract.gold_theorem_7_1
assert_axioms GenLimit.Gold.Text.finiteLanguages_identifiableWith
assert_axioms GenLimit.Gold.Text.finiteLanguages_maximal_semanticallyIdentifiable
assert_axioms GenLimit.Gold.Text.enumerationLearner_identifiesFamily_of_isInclusionAntichain
assert_axioms GenLimit.Gold.Informant.informantEnumerationLearner_identifiesFamily
assert_axioms GenLimit.Gold.Text.exists_locking_of_identifiesLanguage
assert_axioms GenLimit.Gold.Text.superfinite_not_semanticallyIdentifiable
assert_axioms GenLimit.Gold.identifier_implies_fresh_generation
assert_axioms GenLimit.GoldKMSeparation.generation_without_identification
assert_axioms GenLimit.GoldDenseSeparation.dense_generation_without_identification
