/- This file is generated by scripts/build_registry.py. Do not edit. -/
import GenLimit.Paper01_LanguageGeneration.FiniteQuery.ArxivV1
import GenLimit.Paper01_LanguageGeneration.FiniteQuery.Main
import GenLimit.Paper01_LanguageGeneration.Semantic
import GenLimit.Paper01_LanguageGeneration.SetInterface
import GenLimit.Paper02_LearningTheory
import GenLimit.Paper39_DenseGeneration.Patient.History
import GenLimit.Paper39_DenseGeneration.Patient.Main
import Lean.Util.CollectAxioms
import Lean.Elab.Command

open Lean Elab Command

private def registryAllowedAxioms : Array Name :=
  #[``propext, ``Classical.choice, ``Quot.sound].qsort Name.lt

/-- Resolve a registered declaration, verify its defining module, and enforce
the project's logical-dependency allowlist. -/
elab "assert_registered_decl " n:ident " in " expectedModule:ident : command => do
  let name ← liftCoreM <| Lean.Elab.realizeGlobalConstNoOverloadWithInfo n
  let expected := expectedModule.getId
  let env ← getEnv
  let some moduleIdx := env.getModuleIdxFor? name
    | throwError m!"cannot determine defining module for {name}"
  let actual := env.header.moduleNames[moduleIdx.toNat]!
  unless actual == expected do
    throwError m!"wrong defining module for {name}: {actual}; expected {expected}"
  let actualAxioms := (← Lean.collectAxioms name).qsort Name.lt
  unless actualAxioms.all fun ax => registryAllowedAxioms.contains ax do
    throwError m!"unexpected axioms for {name}: {actualAxioms.toList}"
  logInfo m!"{name}: module {actual}, logical dependencies {actualAxioms.toList}"

assert_registered_decl GenLimit.KM.Semantic.kleinbergMullainathan_main in GenLimit.Paper01_LanguageGeneration.Semantic
assert_registered_decl GenLimit.KM.SetInterface.kleinbergMullainathan_set_interface in GenLimit.Paper01_LanguageGeneration.SetInterface
assert_registered_decl GenLimit.KM.SetInterface.kleinbergMullainathan_set_interface_with_repetitions in GenLimit.Paper01_LanguageGeneration.SetInterface
assert_registered_decl GenLimit.LiRamanTewari.theorem_2_5 in GenLimit.Paper02_LearningTheory
assert_registered_decl GenLimit.OracleFamily.ArxivV1.kleinbergMullainathan_main in GenLimit.Paper01_LanguageGeneration.FiniteQuery.ArxivV1
assert_registered_decl GenLimit.OracleFamily.kleinbergMullainathan_main in GenLimit.Paper01_LanguageGeneration.FiniteQuery.Main
assert_registered_decl GenLimit.PatientMachine.output_injective in GenLimit.Paper39_DenseGeneration.Patient.History
assert_registered_decl GenLimit.PatientMachine.patientScope_generation_and_lowerDensity in GenLimit.Paper39_DenseGeneration.Patient.Main
