import GenLimit.Angluin.Locking

/-!
# Existence of locking sequences

This module formalizes the semantic diagonal argument in the necessity half
of Angluin's Theorem 1.  If a learner converges on every positive presentation
of a nonempty target, some finite target-language history must lock all of its
future conjectures.  The resulting lock is extensionally correct, and hence
the locking lemma in `Locking.lean` yields Condition 2 (Corollary 1).

The argument is semantic: it proves existence of a lock.  The stronger
effective construction needed to enumerate the locks uniformly, and thus to
derive Condition 1, remains separate.
-/

namespace GenLimit.Angluin

open GenLimit.Generic

/-- A finite target-language continuation on which the learner changes its
current conjecture. -/
def HasChangeExtension
    (M : List α → ℕ) (L : Generic.Language α) (xs : List α) : Prop :=
  ∃ tail, ListWithin tail L ∧ M (xs ++ tail) ≠ M xs

theorem hasChangeExtension_of_not_locking
    {M : List α → ℕ} {L : Generic.Language α} {xs : List α}
    (hxs : ListWithin xs L)
    (hno : ¬IsLockingSequence M L xs (M xs)) :
    HasChangeExtension M L xs := by
  by_contra h
  apply hno
  constructor
  · exact hxs
  · intro tail htail
    by_contra hchange
    exact h ⟨tail, htail, hchange⟩

/-- Histories whose entries all lie in `L`. -/
abbrev HistoryIn (L : Generic.Language α) :=
  {xs : List α // ListWithin xs L}

theorem listWithin_append
    {L : Generic.Language α} {xs ys : List α}
    (hxs : ListWithin xs L) (hys : ListWithin ys L) :
    ListWithin (xs ++ ys) L := by
  intro x hx
  rw [List.mem_append] at hx
  exact hx.elim (hxs x) (hys x)

theorem singletonWithin
    {L : Generic.Language α} {x : α} (hx : x ∈ L) :
    ListWithin [x] L := by
  simpa [ListWithin]

/-- One diagonal stage first inserts the next value of a fixed presentation,
then appends a target-language continuation causing a mind change. -/
noncomputable def adversarialStep
    (M : List α → ℕ) (L : Generic.Language α)
    (base : Generic.Stream α) (hbase : Generic.StreamIn base L)
    (hchange : ∀ xs, ListWithin xs L → HasChangeExtension M L xs)
    (n : ℕ) (state : HistoryIn L) : HistoryIn L := by
  classical
  let seeded : List α := state.1 ++ [base n]
  have hseeded : ListWithin seeded L :=
    listWithin_append state.2 (singletonWithin (hbase ⟨n, rfl⟩))
  let tail : List α := Classical.choose (hchange seeded hseeded)
  have htail : ListWithin tail L :=
    (Classical.choose_spec (hchange seeded hseeded)).1
  exact ⟨seeded ++ tail, listWithin_append hseeded htail⟩

theorem adversarialStep_eq
    {M : List α → ℕ} {L : Generic.Language α}
    {base : Generic.Stream α} {hbase : Generic.StreamIn base L}
    {hchange : ∀ xs, ListWithin xs L → HasChangeExtension M L xs}
    (n : ℕ) (state : HistoryIn L) :
    (adversarialStep M L base hbase hchange n state).1 =
      let seeded := state.1 ++ [base n]
      seeded ++ Classical.choose
        (hchange seeded
          (listWithin_append state.2
            (singletonWithin (hbase ⟨n, rfl⟩)))) := by
  rfl

/-- The nested histories generated by repeated diagonal stages. -/
noncomputable def adversarialHistory
    (M : List α → ℕ) (L : Generic.Language α)
    (base : Generic.Stream α) (hbase : Generic.StreamIn base L)
    (hchange : ∀ xs, ListWithin xs L → HasChangeExtension M L xs) :
    ℕ → HistoryIn L
  | 0 => ⟨[], by simp [ListWithin]⟩
  | n + 1 => adversarialStep M L base hbase hchange n
      (adversarialHistory M L base hbase hchange n)

theorem adversarialHistory_prefix_succ
    {M : List α → ℕ} {L : Generic.Language α}
    {base : Generic.Stream α} {hbase : Generic.StreamIn base L}
    {hchange : ∀ xs, ListWithin xs L → HasChangeExtension M L xs}
    (n : ℕ) :
    (adversarialHistory M L base hbase hchange n).1 <+:
      (adversarialHistory M L base hbase hchange (n + 1)).1 := by
  rw [adversarialHistory, adversarialStep_eq]
  exact List.IsPrefix.trans (List.prefix_append _ [base n])
    (List.prefix_append _ _)

theorem adversarialHistory_prefix
    {M : List α → ℕ} {L : Generic.Language α}
    {base : Generic.Stream α} {hbase : Generic.StreamIn base L}
    {hchange : ∀ xs, ListWithin xs L → HasChangeExtension M L xs}
    {n m : ℕ} (hnm : n ≤ m) :
    (adversarialHistory M L base hbase hchange n).1 <+:
      (adversarialHistory M L base hbase hchange m).1 := by
  induction m, hnm using Nat.le_induction with
  | base => exact List.prefix_refl _
  | succ m hnm ih =>
      exact ih.trans (adversarialHistory_prefix_succ m)

theorem adversarialHistory_length
    {M : List α → ℕ} {L : Generic.Language α}
    {base : Generic.Stream α} {hbase : Generic.StreamIn base L}
    {hchange : ∀ xs, ListWithin xs L → HasChangeExtension M L xs}
    (n : ℕ) :
    n ≤ (adversarialHistory M L base hbase hchange n).1.length := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [adversarialHistory, adversarialStep_eq]
      simp only [List.length_append, List.length_singleton]
      omega

/-- The infinite stream determined by the compatible diagonal histories. -/
noncomputable def adversarialStream
    (M : List α → ℕ) (L : Generic.Language α)
    (base : Generic.Stream α) (hbase : Generic.StreamIn base L)
    (hchange : ∀ xs, ListWithin xs L → HasChangeExtension M L xs) :
    Generic.Stream α := fun k =>
  let history := (adversarialHistory M L base hbase hchange (k + 1)).1
  history.get ⟨k, by
    have hlen := adversarialHistory_length
      (M := M) (L := L) (base := base) (hbase := hbase)
      (hchange := hchange) (k + 1)
    have : k + 1 ≤ history.length := by
      simpa [history] using hlen
    exact lt_of_lt_of_le (Nat.lt_succ_self k) this⟩

theorem adversarialStream_eq_history_get
    {M : List α → ℕ} {L : Generic.Language α}
    {base : Generic.Stream α} {hbase : Generic.StreamIn base L}
    {hchange : ∀ xs, ListWithin xs L → HasChangeExtension M L xs}
    (n k : ℕ)
    (hk : k < (adversarialHistory M L base hbase hchange n).1.length) :
    adversarialStream M L base hbase hchange k =
      (adversarialHistory M L base hbase hchange n).1.get ⟨k, hk⟩ := by
  rw [adversarialStream]
  have hbound : k <
      (adversarialHistory M L base hbase hchange (k + 1)).1.length := by
    have hlen := adversarialHistory_length
      (M := M) (L := L) (base := base) (hbase := hbase)
      (hchange := hchange) (k + 1)
    omega
  rw [List.get_eq_getElem, List.get_eq_getElem]
  rcases le_total (k + 1) n with hkn | hnk
  · have hp := adversarialHistory_prefix
        (M := M) (L := L) (base := base) (hbase := hbase)
        (hchange := hchange) hkn
    exact (List.prefix_iff_getElem.mp hp).2 k hbound
  · have hp := adversarialHistory_prefix
        (M := M) (L := L) (base := base) (hbase := hbase)
        (hchange := hchange) hnk
    exact ((List.prefix_iff_getElem.mp hp).2 k hk).symm

theorem streamPrefix_adversarialStream
    {M : List α → ℕ} {L : Generic.Language α}
    {base : Generic.Stream α} {hbase : Generic.StreamIn base L}
    {hchange : ∀ xs, ListWithin xs L → HasChangeExtension M L xs}
    (n : ℕ) :
    streamPrefix (adversarialStream M L base hbase hchange)
        (adversarialHistory M L base hbase hchange n).1.length =
      (adversarialHistory M L base hbase hchange n).1 := by
  apply List.ext_get
  · simp [streamPrefix]
  · intro k hkPrefix hkHistory
    simp only [streamPrefix, List.get_ofFn]
    exact adversarialStream_eq_history_get n k hkHistory

theorem streamPrefix_adversarialStream_of_prefix
    {M : List α → ℕ} {L : Generic.Language α}
    {base : Generic.Stream α} {hbase : Generic.StreamIn base L}
    {hchange : ∀ xs, ListWithin xs L → HasChangeExtension M L xs}
    {xs : List α} {n : ℕ}
    (hxs : xs <+:
      (adversarialHistory M L base hbase hchange n).1) :
    streamPrefix (adversarialStream M L base hbase hchange) xs.length = xs := by
  apply List.ext_get
  · simp [streamPrefix]
  · intro k hkStream hkxs
    simp only [streamPrefix, List.get_ofFn]
    have hdiag := adversarialStream_eq_history_get
      (M := M) (L := L) (base := base) (hbase := hbase)
      (hchange := hchange) n k (lt_of_lt_of_le hkxs hxs.length_le)
    have hp := (List.prefix_iff_getElem.mp hxs).2 k hkxs
    rw [List.get_eq_getElem] at hdiag
    rw [List.get_eq_getElem]
    simpa using hdiag.trans hp.symm

theorem adversarialStream_presents
    {M : List α → ℕ} {L : Generic.Language α}
    {base : Generic.Stream α} (hP : Generic.Presents base L)
    {hchange : ∀ xs, ListWithin xs L → HasChangeExtension M L xs} :
    Generic.Presents
      (adversarialStream M L base (Generic.streamIn_of_presents hP) hchange) L := by
  classical
  let hbase := Generic.streamIn_of_presents hP
  apply Set.Subset.antisymm
  · rintro x ⟨k, rfl⟩
    rw [adversarialStream]
    exact (adversarialHistory M L base hbase hchange (k + 1)).2 _
      (List.get_mem _ _)
  · intro x hx
    rw [← hP] at hx
    obtain ⟨n, rfl⟩ := hx
    let history := (adversarialHistory M L base hbase hchange (n + 1)).1
    have hbaseMem : base n ∈ history := by
      dsimp [history]
      rw [adversarialHistory.eq_def, adversarialStep_eq]
      simp
    have hprefix := streamPrefix_adversarialStream
      (M := M) (L := L) (base := base) (hbase := hbase)
      (hchange := hchange) (n + 1)
    change base n ∈
      (adversarialHistory M L base hbase hchange (n + 1)).1 at hbaseMem
    rw [← hprefix] at hbaseMem
    rw [streamPrefix] at hbaseMem
    obtain ⟨i, hi⟩ := List.mem_ofFn.mp hbaseMem
    exact ⟨i, hi⟩

theorem adversarialHistory_mindChange
    {M : List α → ℕ} {L : Generic.Language α}
    {base : Generic.Stream α} {hbase : Generic.StreamIn base L}
    {hchange : ∀ xs, ListWithin xs L → HasChangeExtension M L xs}
    (n : ℕ) :
    let history := (adversarialHistory M L base hbase hchange n).1
    let seeded := history ++ [base n]
    M (adversarialHistory M L base hbase hchange (n + 1)).1 ≠ M seeded := by
  rw [adversarialHistory, adversarialStep_eq]
  exact (Classical.choose_spec
    (hchange _
      (listWithin_append
        (adversarialHistory M L base hbase hchange n).2
        (singletonWithin (hbase ⟨n, rfl⟩))))).2

theorem exists_lockingSequence_of_identifies
    {M : List ℕ → ℕ} {L : Generic.Language ℕ}
    (hL : L.Nonempty)
    (hIdentifies : ∀ stream : Generic.Stream ℕ,
      Generic.Presents stream L → ∃ j, EffectiveConvergesTo M stream j) :
    ∃ xs : List ℕ, ∃ j, IsLockingSequence M L xs j := by
  classical
  by_contra hlocks
  push_neg at hlocks
  have hchange : ∀ xs, ListWithin xs L → HasChangeExtension M L xs := by
    intro xs hxs
    exact hasChangeExtension_of_not_locking hxs (hlocks xs (M xs))
  let base := presentationOfNonempty L hL
  have hbaseP : Generic.Presents base L := presentationOfNonempty_presents L hL
  let hbase := Generic.streamIn_of_presents hbaseP
  let diagonal := adversarialStream M L base hbase hchange
  have hdiagonalP : Generic.Presents diagonal L :=
    adversarialStream_presents (M := M) hbaseP
  obtain ⟨j, T, hconverges⟩ := hIdentifies diagonal hdiagonalP
  let n := T
  let history := (adversarialHistory M L base hbase hchange n).1
  let seeded := history ++ [base n]
  have hseededPrefix :
      streamPrefix diagonal seeded.length = seeded := by
    have hseededHist : seeded <+:
        (adversarialHistory M L base hbase hchange (n + 1)).1 := by
      rw [adversarialHistory, adversarialStep_eq]
      exact List.prefix_append _ _
    exact streamPrefix_adversarialStream_of_prefix hseededHist
  have hnextPrefix := streamPrefix_adversarialStream
    (M := M) (L := L) (base := base) (hbase := hbase)
    (hchange := hchange) (n + 1)
  have hseededLen : T ≤ seeded.length := by
    have hlen := adversarialHistory_length
      (M := M) (L := L) (base := base) (hbase := hbase)
      (hchange := hchange) T
    dsimp [seeded, history, n]
    simp only [List.length_append, List.length_singleton]
    omega
  have hnextLen : T ≤
      (adversarialHistory M L base hbase hchange (n + 1)).1.length := by
    dsimp [n]
    exact le_trans (Nat.le_add_right T 1)
      (adversarialHistory_length (M := M) (L := L) (base := base)
        (hbase := hbase) (hchange := hchange) (T + 1))
  have hseededGuess : M seeded = j := by
    rw [← hseededPrefix]
    exact hconverges _ hseededLen
  have hnextGuess :
      M (adversarialHistory M L base hbase hchange (n + 1)).1 = j := by
    rw [← hnextPrefix]
    exact hconverges _ hnextLen
  exact (adversarialHistory_mindChange
    (M := M) (L := L) (base := base) (hbase := hbase)
    (hchange := hchange) n) (hnextGuess.trans hseededGuess.symm)

/-- A lock obtained for a successfully identified target must name that
target.  Prefix the lock to any presentation and compare its forced output
with the identifier's limiting correct conjecture. -/
theorem lockingSequence_correct_of_identifies
    {C : Generic.LanguageFamily ℕ} {M : List ℕ → ℕ}
    {z j : ℕ} {xs : List ℕ}
    (hL : (C z).Nonempty)
    (hIdentifies : ∀ stream : Generic.Stream ℕ,
      Generic.Presents stream (C z) →
        ∃ ell, C ell = C z ∧ EffectiveConvergesTo M stream ell)
    (hlock : IsLockingSequence M (C z) xs j) :
    C j = C z := by
  let base := presentationOfNonempty (C z) hL
  have hbaseP : Generic.Presents base (C z) :=
    presentationOfNonempty_presents (C z) hL
  let combined := prependStream xs base
  have hcombinedP : Generic.Presents combined (C z) :=
    prependStream_presents hlock.1 hbaseP
  obtain ⟨ell, hell, N, hconverges⟩ := hIdentifies combined hcombinedP
  have hbaseIn : Generic.StreamIn base (C z) :=
    Generic.streamIn_of_presents hbaseP
  have htailIn : ListWithin (streamPrefix base N) (C z) :=
    streamPrefix_listWithin hbaseIn N
  have hlocked : M (xs ++ streamPrefix base N) = j :=
    hlock.2 _ htailIn
  have hprefix :
      streamPrefix combined (xs.length + N) =
        xs ++ streamPrefix base N :=
    streamPrefix_prependStream xs base N
  have hlimit : M (xs ++ streamPrefix base N) = ell := by
    rw [← hprefix]
    exact hconverges _ (Nat.le_add_left N xs.length)
  have hjell : j = ell := hlocked.symm.trans hlimit
  exact (congrArg C hjell).trans hell

/-- Angluin's Corollary 1, with all source effectivity assumptions retained:
effective positive-data inference implies Condition 2. -/
theorem effectiveInferrable_conditionTwo
    {F : EffectiveIndexedFamily} (h : EffectiveInferrable F) :
    ConditionTwo F.language := by
  obtain ⟨M, -, hIdentifies⟩ := h
  apply conditionTwo_of_correctLockingSequences hIdentifies
  intro z
  have hTarget : ∀ stream : Generic.Stream ℕ,
      Generic.Presents stream (F.language z) →
        ∃ j, EffectiveConvergesTo M stream j := by
    intro stream hP
    obtain ⟨j, -, hconv⟩ := hIdentifies z stream hP
    exact ⟨j, hconv⟩
  obtain ⟨xs, j, hlock⟩ :=
    exists_lockingSequence_of_identifies (F.nonempty z) hTarget
  exact ⟨xs, j, hlock,
    lockingSequence_correct_of_identifies (F.nonempty z)
      (hIdentifies z) hlock⟩

theorem corollaryOne (F : EffectiveIndexedFamily) :
    CorollaryOneStatement F := by
  exact effectiveInferrable_conditionTwo

end GenLimit.Angluin
